=== DashaGrigorieva/SC_Java_TrainOrder_XML/data/train.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/train"
        xmlns:tns="http://www.example.com/train"
        elementFormDefault="qualified">
    <element name="orders">
        <complexType>
            <sequence>
                <element name="order"
                         type="tns:order"
                         minOccurs="1"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="order">
        <sequence>
            <element name="name" type="string" />
            <element name="client" type="string" />
            <element name="number" type="positiveInteger" />
            <element name="wagons" type="tns:wagons" />
        </sequence>
    </complexType>
    <complexType name="wagons">
        <sequence>
            <element name="wagon"
                     type="tns:wagon"
                     minOccurs="1"
                     maxOccurs="7" />
        </sequence>
    </complexType>
    <complexType name="wagon">
        <sequence>
            <element name="type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="l" ></enumeration>
                        <enumeration value="vr"></enumeration>
                        <enumeration value="o"></enumeration>
                        <enumeration value="p"></enumeration>
                        <enumeration value="k"></enumeration>
                        <enumeration value="sv"></enumeration>
                        <enumeration value="b"></enumeration>
                    </restriction>
                </simpleType>
            </element>
            <element name="count" type="positiveInteger" />
        </sequence>
    </complexType>
</schema>

=== DashaGrigorieva/SC_Java_TrainOrder_XML/data/train.xml
<?xml version="1.0" encoding="UTF-8"?>
        <orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/train"
        xsi:schemaLocation="http://www.example.com/train train.xsd">
            <order>
                <name>Hogwarts Express</name>
                <client>London Kings-Cross</client>
                <number>1</number>
                <wagons>
                    <wagon>
                        <type>l</type>
                        <count>2</count>
                    </wagon>
                    <wagon>
                        <type>l</type>
                        <count>1</count>
                    </wagon>
                    <wagon>
                        <type>sv</type>
                        <count>2</count>
                    </wagon>
                    <wagon>
                        <type>b</type>
                        <count>3</count>
                    </wagon>
                </wagons>
            </order>
            <order>
                <name>Eastern Express</name>
                <client>Agatha Christie</client>
                <number>4</number>
                <wagons>
                    <wagon>
                        <type>p</type>
                        <count>4</count>
                    </wagon>
                    <wagon>
                        <type>k</type>
                        <count>6</count>
                    </wagon>
                    <wagon>
                        <type>o</type>
                        <count>2</count>
                    </wagon>
                </wagons>
            </order>
            <order>
                <name>Regional</name>
                <client>Gomel Station</client>
                <number>2</number>
                <wagons>
                    <wagon>
                        <type>o</type>
                        <count>4</count>
                    </wagon>
                    <wagon>
                        <type>vr</type>
                        <count>1</count>
                    </wagon>
                    <wagon>
                        <type>b</type>
                        <count>2</count>
                    </wagon>
                </wagons>
            </order>
            <order>
                <name>Passenger</name>
                <client>Minsk Central Station</client>
                <number>4</number>
                <wagons>
                    <wagon>
                        <type>l</type>
                        <count>4</count>
                    </wagon>
                    <wagon>
                        <type>vr</type>
                        <count>1</count>
                    </wagon>
                    <wagon>
                        <type>o</type>
                        <count>2</count>
                    </wagon>
                    <wagon>
                        <type>k</type>
                        <count>7</count>
                    </wagon>
                </wagons>
            </order>
        </orders>
